/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/cupboard.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cupboard.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Wardrobe.geometry} material={materials.Material} scale={[6.11, 4.03, 1]} />
      <mesh geometry={nodes.Plate.geometry} material={nodes.Plate.material} position={[-1.88, 0, 0.06]} rotation={[0, 1.57, 0]} scale={[0.94, 3.89, 0.05]} />
      <mesh geometry={nodes.Plate001.geometry} material={nodes.Plate001.material} position={[-3.97, -0.01, 0.06]} rotation={[0, 1.57, 0]} scale={[0.94, 3.89, 0.05]} />
      <mesh geometry={nodes.Plate002.geometry} material={nodes.Plate002.material} position={[0.2, 0.01, 0]} rotation={[0, 1.57, 0]} scale={[0.94, 3.89, 0.05]} />
      <mesh geometry={nodes.Plate003.geometry} material={nodes.Plate003.material} position={[2.3, -0.02, 0.05]} rotation={[0, 1.57, 0]} scale={[0.94, 3.89, 0.05]} />
      <mesh geometry={nodes.Plate004.geometry} material={nodes.Plate004.material} position={[4.28, 0.01, -0.01]} rotation={[0, 1.57, 0]} scale={[0.94, 3.89, 0.05]} />
      <mesh geometry={nodes.Plate005.geometry} material={nodes.Plate005.material} position={[-2.92, 2.48, 0.02]} rotation={[1.57, 0, -Math.PI / 2]} scale={[0.94, 1.09, 0.05]} />
      <mesh geometry={nodes.Plate006.geometry} material={nodes.Plate006.material} position={[-2.92, 1.15, 0.05]} rotation={[1.57, 0, -Math.PI / 2]} scale={[0.94, 1.09, 0.05]} />
      <mesh geometry={nodes.Plate007.geometry} material={nodes.Plate007.material} position={[-2.91, -0.22, 0.03]} rotation={[1.57, 0, -Math.PI / 2]} scale={[0.94, 1.09, 0.05]} />
      <mesh geometry={nodes.Plate008.geometry} material={nodes.Plate008.material} position={[-2.93, -1.49, 0.03]} rotation={[1.57, 0, -Math.PI / 2]} scale={[0.94, 1.09, 0.05]} />
      <mesh geometry={nodes.Plate009.geometry} material={nodes.Plate009.material} position={[-2.93, -2.78, 0]} rotation={[1.57, 0, -Math.PI / 2]} scale={[0.94, 1.09, 0.05]} />
    </group>
  )
}

useGLTF.preload('/cupboard.gltf')
