/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/shelving.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Shelving(props) {
  const { nodes, materials } = useGLTF('./models/shelving.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} scale={[1, 1.48, 0.3]} />
    </group>
  )
}

useGLTF.preload('./models/shelving.gltf')
