/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/shelving.gltf
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { ConfiguratorProvider, useConfigurator } from '../contexts/Configurator';

import { useFrame } from "@react-three/fiber";
import * as Three from "three";
import { Vector3 } from "three";

export function Shelving(props) {
  const { nodes, materials } = useGLTF('./models/shelving.gltf')

  const {shelfColor} = useConfigurator();
  const shelf = useRef();

  useEffect(()=>{
    materials.Material.color = new Three.Color(shelfColor); }, [shelfColor]); // chinh mau chan ban


  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} scale={[1, 1.48, 0.3]} castShadow
            ref={shelf} />
    </group>
  )
}

useGLTF.preload('./models/shelving.gltf')
